#Makefile generated by NAG Fortran Builder
#The following macros are machine specific
fblib = '../../../../../../../Program Files (x86)/NAG/EFBuilder 6.2/lib'
NI_NAGFOR_Compiler = nagfor
NI_NAGFOR_CompOpts = -ideclient -abi=64 -g -C
NI_NAGFOR_NAGFORInfo = -gfb
NI_NAGFOR_CompOnly = -c
NI_NAGFOR_IFLAGS = 
NI_C_Compiler = nagfor =C
NI_C_CompOpts = -ideclient -abi=64 -g -Wc,-Wall
NI_C_CompOnly = -c
NI_IFLAGS = 
NI_CPP_Compiler = nagfor
NI_ALLOPTS = 
NI_Link = nagfor
NI_LibPath = -L'../../../../../../../Program Files (x86)/NAG/EFBuilder 6.2/lib64' -L$(fblib) 
NI_LDFLAGS = 
NI_RM = fbrm 

#File extensions used in this Makefile
.SUFFIXES:
.SUFFIXES: .f90 .o 

#Output file
NI_OUTPUT = fd1d_heat_explicit.exe

#Target name
NI_TARGET = fd1d_heat_explicit.exe

#Object files
NI_OBJS =	 \
	Types_mod.o \
	RHS_mod.o \
	CFL_mod.o \
	IO_mod.o \
	Solver_mod.o \
	fd1d_heat_explicit.o

#Depend Object files
NI_DOBJS =	 \
	Types_mod.o \
	RHS_mod.o \
	CFL_mod.o \
	IO_mod.o \
	Solver_mod.o \
	fd1d_heat_explicit.o

#Prospective Module files
NI_MODS =	 \
    'cfl_mod.mod' \
    'io_mod.mod' \
    'rhs_mod.mod' \
    'solver_mod.mod' \
    'types_mod.mod'

#Fortran Information files
NI_FIFS =	 \
	Types_mod.fif \
	RHS_mod.fif \
	CFL_mod.fif \
	IO_mod.fif \
	Solver_mod.fif \
	fd1d_heat_explicit.fif

#Library files
NI_LIBS = 

#Dependencies
NI_EQ==
NI_SC=\;
fd1d_heat_explicit.o:	../../fd1d_heat_explicit.f90
fd1d_heat_explicit.o:	types_mod.mod
fd1d_heat_explicit.o:	rhs_mod.mod
fd1d_heat_explicit.o:	cfl_mod.mod
fd1d_heat_explicit.o:	io_mod.mod
fd1d_heat_explicit.o:	solver_mod.mod
CFL_mod.o:	../../CFL_mod.f90
CFL_mod.o:	types_mod.mod
cfl_mod.mod:	../../CFL_mod.f90
cfl_mod.mod:	types_mod.mod
IO_mod.o:	../../IO_mod.f90
IO_mod.o:	types_mod.mod
io_mod.mod:	../../IO_mod.f90
io_mod.mod:	types_mod.mod
RHS_mod.o:	../../RHS_mod.f90
RHS_mod.o:	types_mod.mod
rhs_mod.mod:	../../RHS_mod.f90
rhs_mod.mod:	types_mod.mod
Solver_mod.o:	../../Solver_mod.f90
Solver_mod.o:	types_mod.mod
Solver_mod.o:	rhs_mod.mod
solver_mod.mod:	../../Solver_mod.f90
solver_mod.mod:	types_mod.mod
solver_mod.mod:	rhs_mod.mod
Types_mod.o:	../../Types_mod.f90
types_mod.mod:	../../Types_mod.f90

#Default make target rule
$(NI_TARGET):$(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'fd1d_heat_explicit.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Other rules
Types_mod.o types_mod.mod:
	@echo @nagfor Types_mod.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) Types_mod.fif -c ../../Types_mod.f90
RHS_mod.o rhs_mod.mod:
	@echo @nagfor RHS_mod.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) RHS_mod.fif -c ../../RHS_mod.f90
CFL_mod.o cfl_mod.mod:
	@echo @nagfor CFL_mod.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) CFL_mod.fif -c ../../CFL_mod.f90
IO_mod.o io_mod.mod:
	@echo @nagfor IO_mod.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) IO_mod.fif -c ../../IO_mod.f90
Solver_mod.o solver_mod.mod:
	@echo @nagfor Solver_mod.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) Solver_mod.fif -c ../../Solver_mod.f90
fd1d_heat_explicit.o:
	@echo @nagfor fd1d_heat_explicit.f90
	$(NI_NAGFOR_Compiler) $(NI_IFLAGS) $(NI_NAGFOR_CompOpts) $(NI_NAGFOR_NAGFORInfo) fd1d_heat_explicit.fif -c ../../fd1d_heat_explicit.f90

#Rebuild rule
all:clean $(NI_OBJS)
	@echo @link
	$(NI_Link) -o $(NI_OUTPUT) $(NI_LibPath) @'fd1d_heat_explicit.mako' $(NI_LDFLAGS) $(NI_NAGFOR_CompOpts) $(NI_LIBS)

#Clean rule
clean:
	$(NI_RM) $(NI_OUTPUT)
	$(NI_RM) Types_mod.o RHS_mod.o CFL_mod.o IO_mod.o Solver_mod.o fd1d_heat_explicit.o
	$(NI_RM) $(NI_MODS)
	$(NI_RM) Types_mod.fif RHS_mod.fif CFL_mod.fif IO_mod.fif Solver_mod.fif fd1d_heat_explicit.fif
	$(NI_RM) fbvalwatch.vwi

#Clean all rule
clean_all:
	$(NI_RM) '*.exe' '*.a' '*.dll' '*.o' '*.mod' '*.fif' '*.bak' fbvalwatch.vwi
